(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const i=document.getElementById("jobType"),o=document.getElementById("yachtType"),r=document.getElementById("position"),a=document.getElementById("vesselSize"),e=document.getElementById("keyword"),t=document.getElementById("jobList"),l=[{title:"Service Stewardess",yacht:"Motor",position:"Interior",vesselSize:"31m–50m",type:"Permanent",description:"Provide exceptional service for guests aboard a luxurious new build yacht. A solid knowledge of cocktails and wine is required.",location:"50m Private Yacht, Mediterranean",salary:"€4,500/month",startDate:"Mid-February"},{title:"Deckhand",yacht:"Sailing",position:"Deck",vesselSize:"51m–80m",type:"Seasonal",description:"Support sailing operations, maintain the deck’s cleanliness, assist with technical duties, and participate in mooring and docking procedures. A Yachtmaster qualification is preferred.",location:"52m Sailing Yacht, Caribbean",salary:"$4,000/month",visaRequirement:"B1/B2 Visa",startDate:"ASAP"},{title:"Sous Chef",yacht:"Motor",position:"Galley",vesselSize:"81m–100m",type:"Temporary",description:"Create gourmet meals for guests and crew, handle menu planning and provisioning, and maintain high culinary standards.",location:"81m Motor Yacht",salary:"DOE but competitive",startDate:"March"}];function p(){const s=e.value.toLowerCase(),n=i.value,c=o.value,m=r.value,u=a.value,f=l.filter(d=>{const g=s===""||d.title.toLowerCase().includes(s)||d.description.toLowerCase().includes(s),h=n===""||d.type===n,v=c===""||d.yacht===c,E=m===""||d.position===m,S=u===""||d.vesselSize===u;return g&&h&&v&&E&&S});y(f)}function y(s){if(t.innerHTML="",s.length===0){t.innerHTML="<p>No jobs found.</p>";return}s.forEach(n=>{const c=document.createElement("div");c.classList.add("job"),c.innerHTML=`
                <div>
                    <h3>${n.title} (${n.location})</h3>
                    <p><strong>Type:</strong> ${n.type}</p>
                    <p><strong>Yacht:</strong> ${n.yacht}</p>
                    <p><strong>Position:</strong> ${n.position}</p>
                    <p><strong>Vessel Size:</strong> ${n.vesselSize}</p>
                    <p><strong>Description:</strong> ${n.description}</p>
                    <p><strong>Salary:</strong> ${n.salary}</p>
                    ${n.visaRequirement?`<p><strong>Visa Requirement:</strong> ${n.visaRequirement}</p>`:""}
                    <p><strong>Start Date:</strong> ${n.startDate}</p>
                </div>
                <a href="#contacts" class="apply-btn">Apply</a>
            `,c.querySelector(".apply-btn").addEventListener("click",u=>{u.preventDefault(),document.getElementById("contacts").scrollIntoView({behavior:"smooth"})}),t.appendChild(c)})}[i,o,r,a].forEach(s=>{s.addEventListener("click",()=>{Array.from(s.options).forEach(n=>{n.disabled=!1}),s.options[0].disabled=!0})}),y(l),document.querySelector(".search-bar button").addEventListener("click",p),[i,o,r,a].forEach(s=>{s.addEventListener("change",p)}),e.addEventListener("input",p)});document.getElementById("applyForm").addEventListener("submit",function(i){i.preventDefault();const o=document.getElementById("jobName").value.trim(),r=document.getElementById("firstName").value.trim(),a=document.getElementById("lastName").value.trim(),e=document.getElementById("email").value.trim(),t=document.getElementById("cv").files[0];if(!o||!r||!a||!e||!t){alert("Please fill out all fields.");return}if(!L(e)){alert("Please enter a valid email address.");return}if(!b(t)){alert("Only PDF, DOC, or DOCX files are allowed.");return}alert("Your application has been submitted successfully!")});function L(i){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(i)}function b(i){const o=["pdf","doc","docx"],r=i.name.split(".").pop().toLowerCase();return o.includes(r)}
//# sourceMappingURL=index.js.map
