(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const d=document.getElementById("jobType"),s=document.getElementById("yachtType"),l=document.getElementById("position"),r=document.getElementById("vesselSize"),e=document.getElementById("keyword"),t=document.getElementById("jobList"),c=[{title:"Service Stewardess",type:"Permanent",yacht:"Motor",position:"Interior",vesselSize:"31m-50m",description:"Deliver high-end service aboard a luxurious motor yacht."},{title:"Deckhand",type:"Seasonal",yacht:"Sailing",position:"Deck",vesselSize:"51m-80m",description:"Assist with sailing and maintenance tasks on a sailing yacht."},{title:"Chef",type:"Temporary",yacht:"Motor",position:"Galley",vesselSize:"81m-100m",description:"Prepare gourmet meals for guests aboard a motor yacht."},{title:"Engineer",type:"Permanent",yacht:"Motor",position:"Engineering",vesselSize:"101m+",description:"Maintain and repair engine systems on a luxury yacht."}];function u(){const o=e.value.toLowerCase(),n=d.value,i=s.value,y=l.value,p=r.value,h=c.filter(a=>{const f=o===""||a.title.toLowerCase().includes(o)||a.description.toLowerCase().includes(o),g=n===""||a.type===n,v=i===""||a.yacht===i,S=y===""||a.position===y,E=p===""||a.vesselSize===p;return f&&g&&v&&S&&E});m(h)}function m(o){if(t.innerHTML="",o.length===0){t.innerHTML="<p>No jobs found.</p>";return}o.forEach(n=>{const i=document.createElement("div");i.classList.add("job"),i.innerHTML=`
                <div>
                    <h3>${n.title}</h3>
                    <p><strong>Type:</strong> ${n.type}</p>
                    <p><strong>Yacht:</strong> ${n.yacht}</p>
                    <p><strong>Position:</strong> ${n.position}</p>
                    <p><strong>Vessel Size:</strong> ${n.vesselSize}</p>
                    <p>${n.description}</p>
                </div>
                <a href="#contacts" class="apply-btn">Apply</a>
            `,i.querySelector(".apply-btn").addEventListener("click",p=>{p.preventDefault(),document.getElementById("contacts").scrollIntoView({behavior:"smooth"})}),t.appendChild(i)})}[d,s,l,r].forEach(o=>{o.addEventListener("click",()=>{Array.from(o.options).forEach(n=>{n.disabled=!1}),o.options[0].disabled=!0})}),m(c),document.querySelector(".search-bar button").addEventListener("click",u),[d,s,l,r].forEach(o=>{o.addEventListener("change",u)}),e.addEventListener("input",u)});
//# sourceMappingURL=index.js.map
